// 中文版 UI strings — 简体中文 (zh-CN) for the entire marketplace.
// Generated by hand for the 38 engines + UI labels. Translations follow i18n best practices:
// 1. Consistent terminology (记忆 = memory, 引擎 = engine, 检索 = retrieval).
// 2. Technical concepts kept in EN where translation dilutes clarity (HNSW, ANN, TF-IDF).
// 3. Short labels for UI; longer Chinese natural sentences for descriptions.

export type Locale = 'en' | 'zh';

export const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    'app.brand.title': 'Agent Memory Marketplace',
    'app.brand.subtitle': 'Curated registry for AI agent memory engines',
    'app.hero.title': 'Discover AI Agent Memory Engines',
    'app.hero.description': 'A curated marketplace of long-term memory layers for AI agents — search, integrate, and benchmark engines inspired by TencentDB Agent Memory, Letta, Zep, and the open-source agent-memory ecosystem.',
    'app.hero.stats.engines': 'engines indexed',
    'app.hero.stats.layers': 'layers',
    'app.hero.stats.installs': 'cumulative installs',
    'app.search.placeholder': 'Search engines by name, description, or use case…',
    'app.toolbar.sort': 'Sort',
    'app.toolbar.sort.installed': 'Most installed',
    'app.toolbar.sort.rating': 'Highest rated',
    'app.toolbar.sort.name': 'Alphabetical',
    'app.toolbar.layer': 'Layer',
    'app.toolbar.layer.all': 'All',
    'app.card.try_now': 'try now',
    'app.card.try_now_active': '✓ try now',
    'app.card.show_code': 'show code',
    'app.card.hide_code': 'hide code',
    'app.card.when': 'When',
    'app.card.installs': 'installs',
    'app.modal.steps': 'Steps',
    'app.modal.output': 'Output',
    'app.modal.close': 'close',
    'app.empty.title': 'No engines match',
    'app.empty.description': 'Try a different search term or layer filter.',
    'app.footer': 'Built with vanilla TS + zero-dep runtime + esbuild · Theme-aware CSS · {n} engines indexed · open source MIT',
    'app.lang.label': 'Language',
    'app.lang.en': 'EN',
    'app.lang.zh': '中文',
    'app.theme.label': 'Theme',
    'app.theme.light': 'light',
    'app.theme.dark': 'dark',
    'app.theme.sepia': 'sepia',
    'app.theme.nord': 'nord',
    'app.meta.installs_label': 'installs',
  },
  zh: {
    'app.brand.title': '智能体记忆引擎市场',
    'app.brand.subtitle': 'AI 智能体记忆引擎的精选注册中心',
    'app.hero.title': '发现 AI 智能体记忆引擎',
    'app.hero.description': '面向 AI 智能体的长期记忆层精选市场 — 搜索、集成、对比评测引擎。灵感来自 TencentDB Agent Memory、Letta、Zep 和开源 agent-memory 生态。',
    'app.hero.stats.engines': '个引擎',
    'app.hero.stats.layers': '个层级',
    'app.hero.stats.installs': '累计安装量',
    'app.search.placeholder': '按名称、描述或使用场景搜索引擎…',
    'app.toolbar.sort': '排序',
    'app.toolbar.sort.installed': '最多安装',
    'app.toolbar.sort.rating': '最高评分',
    'app.toolbar.sort.name': '字母顺序',
    'app.toolbar.layer': '层级',
    'app.toolbar.layer.all': '全部',
    'app.card.try_now': '立即试用',
    'app.card.try_now_active': '✓ 试用中',
    'app.card.show_code': '查看代码',
    'app.card.hide_code': '隐藏代码',
    'app.card.when': '使用场景',
    'app.card.installs': '次安装',
    'app.modal.steps': '执行步骤',
    'app.modal.output': '输出结果',
    'app.modal.close': '关闭',
    'app.empty.title': '未找到匹配引擎',
    'app.empty.description': '请尝试不同的搜索词或层级筛选。',
    'app.footer': '基于 vanilla TS + 零依赖运行时 + esbuild 构建 · 主题感知 CSS · {n} 个引擎 · 开源 MIT',
    'app.lang.label': '语言',
    'app.lang.en': 'EN',
    'app.lang.zh': '中文',
    'app.theme.label': '主题',
    'app.theme.light': '明亮',
    'app.theme.dark': '暗黑',
    'app.theme.sepia': '复古',
    'app.theme.nord': '极地',
    'app.meta.installs_label': '次安装',
  },
};

export const t = (key: string, locale: Locale = 'en', vars: Record<string, unknown> | null = null): string => {
  const tmpl = STRINGS[locale]?.[key] ?? STRINGS.en[key] ?? key;
  if (!vars) return tmpl;
  return Object.entries(vars).reduce(
    (acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)),
    tmpl,
  );
};

// Layer translations
export const LAYER_LABELS: Record<Locale, Record<string, string>> = {
  en: {
    episodic: 'Episodic',
    semantic: 'Semantic',
    procedural: 'Procedural',
    consolidation: 'Consolidation',
    'short-term': 'Short-term',
    'long-term': 'Long-term',
    working: 'Working',
    associative: 'Associative',
    compressor: 'Compressor',
    integration: 'Integration',
    memvector: 'MemVector',
  },
  zh: {
    episodic: '事件记忆',
    semantic: '语义记忆',
    procedural: '程序记忆',
    consolidation: '整合压缩',
    'short-term': '短期记忆',
    'long-term': '长期记忆',
    working: '工作记忆',
    associative: '联想记忆',
    compressor: '压缩层',
    integration: '集成层',
    memvector: '向量检索',
  },
};

export const LAYER_DESCS: Record<Locale, Record<string, string>> = {
  en: {
    episodic: 'Time-stamped event records',
    semantic: 'Tag-based indexing & retrieval',
    procedural: 'Procedure caching',
    consolidation: 'Dedup, decay, tiering',
    'short-term': 'Bounded rolling windows',
    'long-term': 'Permanent key-value storage',
    working: 'Attention-decay active reasoning',
    associative: 'Graph-based link recall',
    compressor: 'Compression & ratio',
    integration: 'Dashboard, audit, profiling',
    memvector: 'ANN + hybrid vector search',
  },
  zh: {
    episodic: '带时间戳的事件记录',
    semantic: '基于标签的索引与检索',
    procedural: '程序步骤缓存',
    consolidation: '去重、衰减、分层',
    'short-term': '有界滚动窗口',
    'long-term': '永久键值存储',
    working: '注意力衰减推理',
    associative: '图关联回忆',
    compressor: '压缩与比例',
    integration: '仪表盘、审计、画像',
    memvector: '近似最近邻 + 混合向量检索',
  },
};
